### ISSUE TITLE
执行到快速部署 [2]的时候报错

### ISSUE THREAD

**Issue by cyhank** [maq128/temp#1]
[root@localhost deploy]# python ./deploy.py all
Traceback (most recent call last):
  File "./deploy.py", line 7, in <module>
    import comm.tarsTest as tarsTest
  File "/data/Tars/deploy/comm/tarsTest.py", line 6, in <module>
    import requests
ImportError: No module named requests

执行到python ./deploy.py all的时候出现上面的错误,请问是什么原因?

**Comment by maq128** [comment]
检查过 python 版本吗？

**Comment by cyhank** [comment]
是2.7.5的

**Comment by maq128** [comment]
试试 yum install python-requests 吧。

**Comment by cyhank** [comment]
更新了版本之后可以继续跑,启动之后是这样的
> Tars@0.1.0 prd /usr/local/app/web
> pm2 start bin/www --name=tars-node-web

[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
[PM2] Starting /usr/local/app/web/bin/www in fork_mode (1 instance)
[PM2] Done.
┌───────────────┬────┬─────────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
│ App name      │ id │ version │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
├───────────────┼────┼─────────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
│ tars-node-web │ 0  │ 0.1.0   │ fork │ 13029 │ online │ 0       │ 0s     │ 0%  │ 13.2 MB   │ root │ disabled │
└───────────────┴────┴─────────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app


看起来好像没问题,但是3000端口没跑起来,log最后报的信息是
at  Module.load (internal/modules/cjs/loader.js:598:32)"],"level":"error","message":"uncaughtException: Cannot find module '@tars/registry'","timestamp":"2018-11-29 17:19:38.246"}

@tars/registry这个东西没找到是在哪里..

**Comment by maq128** [comment]
还是到官方 QQ 群里继续讨论吧，这里不方便讨论太细的内容。
